ALTER TABLE T_PRODUCT ADD COLUMN status INT NOT NULL DEFAULT 0;
ALTER TABLE T_PRODUCT ADD COLUMN published TIMESTAMPTZ;

ALTER TABLE T_CATEGORY ADD COLUMN product_count INT NOT NULL DEFAULT 0;
ALTER TABLE T_CATEGORY ADD COLUMN published_product_count INT NOT NULL DEFAULT 0;

ALTER TABLE T_SECTION ADD COLUMN published_product_count INT NOT NULL DEFAULT 0;
