ALTER TABLE T_MERCHANT ADD COLUMN total_views BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN total_shares BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN total_chats BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN total_sales BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN total_orders BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN score DECIMAL(20,4) NOT NULL DEFAULT 0;
ALTER TABLE T_MERCHANT ADD COLUMN conversion DECIMAL(20,4) NOT NULL DEFAULT 0;
