-- Reset categories
DROP TABLE T_PRODUCT_CATEGORY;
DROP TABLE T_CATEGORY;
CREATE TABLE T_CATEGORY(
    id              BIGINT NOT NULL,

    title           VARCHAR(100) NOT NULL,
    title_french    VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);

ALTER TABLE T_CATEGORY ADD COLUMN parent_fk BIGINT REFERENCES T_CATEGORY(id);

-- Reset product
DELETE FROM T_PICTURE;
DELETE FROM T_PRODUCT;
ALTER TABLE T_PRODUCT ADD COLUMN category_fk BIGINT NOT NULL REFERENCES T_CATEGORY(id);
ALTER TABLE T_PRODUCT ADD COLUMN sub_category_fk BIGINT NOT NULL REFERENCES T_CATEGORY(id);
